* Import ICPSR file 08297-0006, Transcript Records (Type 1)

program define use_ICPSR_08297_0006_transcript

    if "$ICPSR_08297" == "" {
      display as error "Set global macro ICPSR_08297"
      error 601
    }
    if "$dctdir" == "" {
      display as error "Set global macro dctdir"
      error 601
    }
    
    clear
    
    label define BYPARTF 0 "NON PARTICIPANT" 1 "PARTICIPATED"
    label define FU1PARTF 0 "NON PARTICIPANT" 1 "PARTICIPATED"
    label define FUSTTYPF 1 "IN SCHOOL" 2 "DROPOUT" 3 "TRANSFER" 4 "EARLY GRAD"
    label define TESTFLAF 0 "NOT AVAILABLE" 1 "AVAILABLE"
    label define PARFLAGF 0 "NOT AVAILABLE" 1 "AVAILABLE"
    label define TWINFLAF 0 "NOT A TWIN" 1 "TWIN"
    label define SCHSAMPF 0 "REGULAR SAMPLE" 1 "ALTERNATIVE SCHOOLS" 2 "CUBAN HISPANIC PUBL" 3 "OTHER HISPANIC PUBL" 5 "REGULAR CATHOLIC" 6 "BLACK CATHOLIC" 7 "CUBAN HISPANIC CATH" 8 "ELITE OTHER PRIVATE" 9 "OTHER PRIVATE"
    label define SCHURBF 1 "URBAN" 2 "SUBURBAN" 3 "RURAL"
    label define SCHREGNF 1 "NEW ENGLAND" 2 "MIDDLE ATLANTIC" 3 "SOUTH ATLANTIC" 4 "EAST SOUTH CENTRAL" 5 "WEST SOUTH CENTRAL" 6 "EAST NORTH CENTRAL" 7 "WEST NORTH CENTRAL" 8 "MOUNTAIN" 9 "PACIFIC"
    label define SEXF 1 "MALE" 2 "FEMALE"
    label define RACEF 1 "HISPANIC OR SPANISH" 2 "AMERINDIAN" 3 "ASIAN, PCFC ISLNDR" 4 "BLACK" 5 "WHITE" 6 "OTHER"
    label define BYTESTQF 1 "LOW" 2 "MID-LOW" 3 "MID-HIGH" 4 "HIGH" 8 "{MISSING}" 9 "{LEGIT SKIP}"
    label define FUTESTQF 1 "LOW" 2 "MID-LOW" 3 "MID-HIGH" 4 "HIGH" 8 "{MISSING}" 9 "{LEGIT SKIP}"
    label define FUSESQF 1 "LOW" 2 "MID-LOW" 3 "MID-HIGH" 4 "HIGH" 8 "{MISSING}" 9 "{LEGIT SKIP}"
    label define BYHSPROF 1 "GENERAL" 2 "COLLEGE PREP" 3 "AGRICULTURE" 4 "BUSINESS" 5 "DISTRIBUTIVE EDUC" 6 "HEALTH OCCUP" 7 "HOME ECONOMICS" 8 "TECHNICAL OCCUP" 9 "TRADE INDUSTRIAL" 96 "{MULTIPLE RESPONSE}" 97 "{REFUSAL}" 98 "{NOT DETERMINED}"
    label define FUHSPROF 1 "GENERAL" 2 "COLLEGE PREP" 3 "AGRICULTURE" 4 "BUSINESS" 5 "DISTRIBUTIVE EDUC" 6 "HEALTH OCCUP" 7 "HOME ECONOMICS" 8 "TECHNICAL OCCUP" 9 "TRADE INDUSTRIAL" 96 "{MULTIPLE RESPONSE}" 97 "{REFUSAL}" 98 "{NOT DETERMINED}" 99 "{DIDN^T ATTEND}"
    label define BYHSGRAF 1 "MOSTLY A" 2 "A & B" 3 "MOSTLY B" 4 "B & C" 5 "MOSTLY C" 6 "C & D" 7 "MOSTLY D" 8 "BELOW D" 96 "{MULTIPLE RESPONSE}" 97 "{REFUSAL}" 98 "{NOT DETERMINED}"
    label define FUHSGRAF 1 "MOSTLY A" 2 "A & B" 3 "MOSTLY B" 4 "B & C" 5 "MOSTLY C" 6 "C & D" 7 "MOSTLY D" 8 "BELOW D" 96 "{MULTIPLE RESPONSE}" 97 "{REFUSAL}" 98 "{NOT DETERMINED}" 99 "{DIDN^T ATTEND}"
    label define NOCATF 0 "COURSE OFFERINGS MIS" 1 "COURSE OFFERINGS PRE"
    label define ENROLLEF 1 "SPECIAL EDUCATION" 2 "BILINGUAL DUCATION" 3 "GIFTED" 4 "SPECIAL & BILINGUAL" 5 "GIFTED & BILINGUAL" 6 "{NOT PROVIDED}" 8 "{NOT DETERMINED}"
    label define MONLEFTF 1 "{1}" 2 "{2}" 3 "{3}" 4 "{4}" 5 "{5}" 6 "{6}" 7 "{7}" 8 "{8}" 9 "{9}" 10 "{10}" 11 "{11}" 12 "{12}" 98 "{NOT DETERMINED}"
    label define YEARLEFF 79 "{79}" 80 "{80}" 81 "{81}" 82 "{82}" 83 "{83}" 98 "{NOT DETERMINED}"
    label define RESNLEFF 1 "GRADUATED" 2 "TRANSFERRED" 3 "DROPPED OUT" 4 "EXPELLED" 5 "OTHER" 8 "{NOT DETERMINED}"
    label define DAYSUSPF 1 "{1}" 2 "{2}" 5 "{5}" 20 "{20}" 98 "{NOT DETERMINED}"

    infile using "$dctdir/08297-0006-1.dct" if RECTYPE == 1, using("$ICPSR_08297/DS0006/08297-0006-Data.txt")
    
    replace FUSES = FUSES / 1000
    
    label data ICPSR_08297_0006_transcript

end
