* Import ICPSR file 07896-0004

program define use_ICPSR_07896_0004

    if "$ICPSR_07896" == "" {
      display as error "Set global macro ICPSR_07896"
      error 601
    }
    if "$dctdir" == "" {
      display as error "Set global macro dctdir"
      error 601
    }
    
    clear
    
    label define LB11 1 "ENGLISH" 2 "SPANISH" 3 "ITALIAN" 4 "CHINESE" 5 "FRENCH" 6 "GERMAN" 7 "GREEK" 8 "PORTUGUESE" 9 "FILIPINO" 10 "POLISH" 11 "OTHER" 12 "ENGLISH & SPANISH" 13 "ENGLISH & ITALIAN" 14 "ENGLISH & CHINESE" 15 "ENGLISH & FRENCH" 16 "ENGLISH & GERMAN" 17 "ENGLISH & GREEK" 18 "ENGLISH & PORTUGUESE" 19 "ENGLISH & FILIPINO" 20 "SPANISH & POLISH" 21 "SPANISH & OTHER" 22 "ENGLISH & POLISH" 23 "SPANISH & ITALIAN" 24 "SPANISH & CHINESE" 25 "SPANISH & FRENCH" 27 "SPANISH & GREEK" 30 "ITALIAN & POLISH" 31 "ITALIAN & OTHER" 33 "TWO OTHER LANGUAGES" 41 "CHINESE & OTHER" 51 "FRENCH & OTHER" 81 "PORTUGUESE & OTHER" 95 "DONT KNOW" 96 "MULT PUNCH" 97 "REFUSED" 98 "MISSING" 99 "LEGIT SKIP"
    label define LB12 1 "NO OTHER LANG" 2 "ENGLISH" 3 "SPANISH" 4 "ITALIAN" 5 "CHINESE" 6 "FRENCH" 7 "GERMAN" 8 "GREEK" 9 "PORTUGUESE" 10 "FILIPINO" 11 "POLISH" 12 "OTHER" 20 "ENGLISH & FILIPINO" 21 "ENGLISH & POLISH" 22 "ENGLISH & OTHER" 23 "ENGLISH & SPANISH" 24 "ENGLISH & ITALIAN" 25 "ENGLISH & CHINESE" 26 "ENGLISH & FRENCH" 27 "ENGLISH & GERMAN" 28 "ENGLISH & GREEK" 29 "ENGLISH & PORTUGUESE" 30 "SPANISH & FILIPINO" 31 "SPANISH & POLISH" 32 "SPANISH & OTHER" 34 "SPANISH & ITALIAN" 36 "SPANISH & FRENCH" 37 "SPANISH & GERMAN" 38 "SPANISH & GREEK" 41 "ITALIAN & POLISH" 42 "ITALIAN & OTHER" 44 "FILIPINO & OTHER" 46 "ITALIAN & FRENCH" 47 "ITALIAN & GERMAN" 48 "ITALIAN & GREEK" 50 "CHINESE & FILIPINO" 52 "CHINESE & OTHER" 55 "POLISH & OTHER" 60 "FRENCH & FILIPINO" 61 "FRENCH & POLISH" 62 "FRENCH & OTHER" 67 "FRENCH & GERMAN" 69 "FRENCH & PORTUGUESE" 70 "GERMAN & FILIPINO" 71 "GERMAN & POLISH" 72 "GERMAN & OTHER" 78 "GERMAN & GREEK" 79 "GERMAN & PORTUGUESE" 95 "DONT KNOW" 96 "MULT PUNCH" 97 "REFUSED" 98 "MISSING" 99 "LEGIT SKIP"
    label define LB13 1 "ENGLISH" 2 "SPANISH" 3 "ITALIAN" 4 "CHINESE" 5 "FRENCH" 6 "GERMAN" 7 "GREEK" 8 "PORTUGUESE" 9 "FILIPINO" 10 "POLISH" 11 "OTHER" 12 "ENGLISH & SPANISH" 13 "ENGLISH & ITALIAN" 14 "ENGLISH & CHINESE" 15 "ENGLISH & FRENCH" 16 "ENGLISH & GERMAN" 17 "ENGLISH & GREEK" 18 "ENGLISH & PORTUGUESE" 19 "ENGLISH & FILIPINO" 20 "SPANISH & POLISH" 21 "SPANISH & OTHER" 22 "ENGLISH & POLISH" 23 "SPANISH & ITALIAN" 24 "SPANISH & CHINESE" 25 "SPANISH & FRENCH" 27 "SPANISH & GREEK" 30 "ITALIAN & POLISH" 31 "ITALIAN & OTHER" 33 "TWO OTHER LANGUAGES" 41 "CHINESE & OTHER" 51 "FRENCH & OTHER" 81 "PORTUGUESE & OTHER" 95 "DONT KNOW" 96 "MULT PUNCH" 97 "REFUSED" 98 "MISSING" 99 "LEGIT SKIP"
    label define LB14 1 "ENGLISH" 2 "SPANISH" 3 "ITALIAN" 4 "CHINESE" 5 "FRENCH" 6 "GERMAN" 7 "GREEK" 8 "PORTUGUESE" 9 "FILIPINO" 10 "POLISH" 11 "OTHER" 12 "ENGLISH & SPANISH" 13 "ENGLISH & ITALIAN" 14 "ENGLISH & CHINESE" 15 "ENGLISH & FRENCH" 16 "ENGLISH & GERMAN" 17 "ENGLISH & GREEK" 18 "ENGLISH & PORTUGUESE" 19 "ENGLISH & FILIPINO" 20 "SPANISH & POLISH" 21 "SPANISH & OTHER" 22 "ENGLISH & POLISH" 23 "SPANISH & ITALIAN" 24 "SPANISH & CHINESE" 25 "SPANISH & FRENCH" 27 "SPANISH & GREEK" 30 "ITALIAN & POLISH" 31 "ITALIAN & OTHER" 33 "TWO OTHER LANGUAGES" 41 "CHINESE & OTHER" 51 "FRENCH & OTHER" 81 "PORTUGUESE & OTHER" 95 "DONT KNOW" 96 "MULT PUNCH" 97 "REFUSED" 98 "MISSING" 99 "LEGIT SKIP"
    label define LB15 1 "NO OTHER LANG" 2 "ENGLISH" 3 "SPANISH" 4 "ITALIAN" 5 "CHINESE" 6 "FRENCH" 7 "GERMAN" 8 "GREEK" 9 "PORTUGUESE" 10 "FILIPINO" 11 "POLISH" 12 "OTHER" 20 "ENGLISH & FILIPINO" 21 "ENGLISH & POLISH" 22 "ENGLISH & OTHER" 23 "ENGLISH & SPANISH" 24 "ENGLISH & ITALIAN" 25 "ENGLISH & CHINESE" 26 "ENGLISH & FRENCH" 27 "ENGLISH & GERMAN" 28 "ENGLISH & GREEK" 29 "ENGLISH & PORTUGUESE" 30 "SPANISH & FILIPINO" 31 "SPANISH & POLISH" 32 "SPANISH & OTHER" 34 "SPANISH & ITALIAN" 36 "SPANISH & FRENCH" 37 "SPANISH & GERMAN" 38 "SPANISH & GREEK" 41 "ITALIAN & POLISH" 42 "ITALIAN & OTHER" 44 "FILIPINO & OTHER" 46 "ITALIAN & FRENCH" 47 "ITALIAN & GERMAN" 48 "ITALIAN & GREEK" 50 "CHINESE & FILIPINO" 52 "CHINESE & OTHER" 55 "POLISH & OTHER" 60 "FRENCH & FILIPINO" 61 "FRENCH & POLISH" 62 "FRENCH & OTHER" 67 "FRENCH & GERMAN" 69 "FRENCH & PORTUGUESE" 70 "GERMAN & FILIPINO" 71 "GERMAN & POLISH" 72 "GERMAN & OTHER" 78 "GERMAN & GREEK" 79 "GERMAN & PORTUGUESE" 95 "DONT KNOW" 96 "MULT PUNCH" 97 "REFUSED" 98 "MISSING" 99 "LEGIT SKIP"
    label define LB16 1 "NO OTHER LANG" 2 "ENGLISH" 3 "SPANISH" 4 "ITALIAN" 5 "CHINESE" 6 "FRENCH" 7 "GERMAN" 8 "GREEK" 9 "PORTUGUESE" 10 "FILIPINO" 11 "POLISH" 12 "OTHER" 20 "ENGLISH & FILIPINO" 21 "ENGLISH & POLISH" 22 "ENGLISH & OTHER" 23 "ENGLISH & SPANISH" 24 "ENGLISH & ITALIAN" 25 "ENGLISH & CHINESE" 26 "ENGLISH & FRENCH" 27 "ENGLISH & GERMAN" 28 "ENGLISH & GREEK" 29 "ENGLISH & PORTUGUESE" 30 "SPANISH & FILIPINO" 31 "SPANISH & POLISH" 32 "SPANISH & OTHER" 34 "SPANISH & ITALIAN" 36 "SPANISH & FRENCH" 37 "SPANISH & GERMAN" 38 "SPANISH & GREEK" 41 "ITALIAN & POLISH" 42 "ITALIAN & OTHER" 44 "FILIPINO & OTHER" 46 "ITALIAN & FRENCH" 47 "ITALIAN & GERMAN" 48 "ITALIAN & GREEK" 50 "CHINESE & FILIPINO" 52 "CHINESE & OTHER" 55 "POLISH & OTHER" 60 "FRENCH & FILIPINO" 61 "FRENCH & POLISH" 62 "FRENCH & OTHER" 67 "FRENCH & GERMAN" 69 "FRENCH & PORTUGUESE" 70 "GERMAN & FILIPINO" 71 "GERMAN & POLISH" 72 "GERMAN & OTHER" 78 "GERMAN & GREEK" 79 "GERMAN & PORTUGUESE" 95 "DONT KNOW" 96 "MULT PUNCH" 97 "REFUSED" 98 "MISSING" 99 "LEGIT SKIP"
    label define LB17A 1 "VERY WELL" 2 "PRETTY WELL" 3 "NOT VERY WELL" 4 "NOT AT ALL" 5 "DONT KNOW" 6 "MULT PUNCH" 7 "REFUSED" 8 "MISSING" 9 "LEGIT SKIP"
    label define LB17B 1 "VERY WELL" 2 "PRETTY WELL" 3 "NOT VERY WELL" 4 "NOT AT ALL" 5 "DONT KNOW" 6 "MULT PUNCH" 7 "REFUSED" 8 "MISSING" 9 "LEGIT SKIP"
    label define LB17C 1 "VERY WELL" 2 "PRETTY WELL" 3 "NOT VERY WELL" 4 "NOT AT ALL" 5 "DONT KNOW" 6 "MULT PUNCH" 7 "REFUSED" 8 "MISSING" 9 "LEGIT SKIP"
    label define LB17D 1 "VERY WELL" 2 "PRETTY WELL" 3 "NOT VERY WELL" 4 "NOT AT ALL" 5 "DONT KNOW" 6 "MULT PUNCH" 7 "REFUSED" 8 "MISSING" 9 "LEGIT SKIP"
    label define LB18A 1 "ALWAYS OR ALMOST" 2 "MOSTLY" 3 "ABOUT HALF TIME" 4 "SOMETIMES" 5 "NEVER" 6 "DOES NOT APPLY" 95 "DONT KNOW" 96 "MULT PUNCH" 97 "REFUSED" 98 "MISSING" 99 "LEGIT SKIP"
    label define LB18B 1 "ALWAYS OR ALMOST" 2 "MOSTLY" 3 "ABOUT HALF TIME" 4 "SOMETIMES" 5 "NEVER" 6 "DOES NOT APPLY" 95 "DONT KNOW" 96 "MULT PUNCH" 97 "REFUSED" 98 "MISSING" 99 "LEGIT SKIP"
    label define LB18C 1 "ALWAYS OR ALMOST" 2 "MOSTLY" 3 "ABOUT HALF TIME" 4 "SOMETIMES" 5 "NEVER" 6 "DOES NOT APPLY" 95 "DONT KNOW" 96 "MULT PUNCH" 97 "REFUSED" 98 "MISSING" 99 "LEGIT SKIP"
    label define LB18D 1 "ALWAYS OR ALMOST" 2 "MOSTLY" 3 "ABOUT HALF TIME" 4 "SOMETIMES" 5 "NEVER" 6 "DOES NOT APPLY" 95 "DONT KNOW" 96 "MULT PUNCH" 97 "REFUSED" 98 "MISSING" 99 "LEGIT SKIP"
    label define LB18E 1 "ALWAYS OR ALMOST" 2 "MOSTLY" 3 "ABOUT HALF TIME" 4 "SOMETIMES" 5 "NEVER" 6 "DOES NOT APPLY" 95 "DONT KNOW" 96 "MULT PUNCH" 97 "REFUSED" 98 "MISSING" 99 "LEGIT SKIP"
    label define LB18F 1 "ALWAYS OR ALMOST" 2 "MOSTLY" 3 "ABOUT HALF TIME" 4 "SOMETIMES" 5 "NEVER" 6 "DOES NOT APPLY" 95 "DONT KNOW" 96 "MULT PUNCH" 97 "REFUSED" 98 "MISSING" 99 "LEGIT SKIP"
    label define LB18G 1 "ALWAYS OR ALMOST" 2 "MOSTLY" 3 "ABOUT HALF TIME" 4 "SOMETIMES" 5 "NEVER" 6 "DOES NOT APPLY" 95 "DONT KNOW" 96 "MULT PUNCH" 97 "REFUSED" 98 "MISSING" 99 "LEGIT SKIP"
    label define LB18H 1 "ALWAYS OR ALMOST" 2 "MOSTLY" 3 "ABOUT HALF TIME" 4 "SOMETIMES" 5 "NEVER" 6 "DOES NOT APPLY" 95 "DONT KNOW" 96 "MULT PUNCH" 97 "REFUSED" 98 "MISSING" 99 "LEGIT SKIP"
    label define LB18I 1 "ALWAYS OR ALMOST" 2 "MOSTLY" 3 "ABOUT HALF TIME" 4 "SOMETIMES" 5 "NEVER" 6 "DOES NOT APPLY" 95 "DONT KNOW" 96 "MULT PUNCH" 97 "REFUSED" 98 "MISSING" 99 "LEGIT SKIP"
    label define LB18J 1 "ALWAYS OR ALMOST" 2 "MOSTLY" 3 "ABOUT HALF TIME" 4 "SOMETIMES" 5 "NEVER" 6 "DOES NOT APPLY" 95 "DONT KNOW" 96 "MULT PUNCH" 97 "REFUSED" 98 "MISSING" 99 "LEGIT SKIP"
    label define LB19A 1 "VERY WELL" 2 "PRETTY WELL" 3 "NOT VERY WELL" 4 "NOT AT ALL" 5 "DONT KNOW" 6 "MULT PUNCH" 7 "REFUSED" 8 "MISSING" 9 "LEGIT SKIP"
    label define LB19B 1 "VERY WELL" 2 "PRETTY WELL" 3 "NOT VERY WELL" 4 "NOT AT ALL" 5 "DONT KNOW" 6 "MULT PUNCH" 7 "REFUSED" 8 "MISSING" 9 "LEGIT SKIP"
    label define LB19C 1 "VERY WELL" 2 "PRETTY WELL" 3 "NOT VERY WELL" 4 "NOT AT ALL" 5 "DONT KNOW" 6 "MULT PUNCH" 7 "REFUSED" 8 "MISSING" 9 "LEGIT SKIP"
    label define LB19D 1 "VERY WELL" 2 "PRETTY WELL" 3 "NOT VERY WELL" 4 "NOT AT ALL" 5 "DONT KNOW" 6 "MULT PUNCH" 7 "REFUSED" 8 "MISSING" 9 "LEGIT SKIP"
    label define LB20A 1 "YES" 2 "NO" 3 "NOT IN USA THEN" 5 "DONT KNOW" 6 "MULT PUNCH" 7 "REFUSED" 8 "MISSING" 9 "LEGIT SKIP"
    label define LB20B 1 "YES" 2 "NO" 3 "NOT IN USA THEN" 5 "DONT KNOW" 6 "MULT PUNCH" 7 "REFUSED" 8 "MISSING" 9 "LEGIT SKIP"
    label define LB20C 1 "YES" 2 "NO" 3 "NOT IN USA THEN" 5 "DONT KNOW" 6 "MULT PUNCH" 7 "REFUSED" 8 "MISSING" 9 "LEGIT SKIP"
    label define LB20D 1 "YES" 2 "NO" 3 "NOT IN USA THEN" 5 "DONT KNOW" 6 "MULT PUNCH" 7 "REFUSED" 8 "MISSING" 9 "LEGIT SKIP"
    label define LB21A 1 "YES" 2 "NO" 3 "NOT IN USA THEN" 5 "DONT KNOW" 6 "MULT PUNCH" 7 "REFUSED" 8 "MISSING" 9 "LEGIT SKIP"
    label define LB21B 1 "YES" 2 "NO" 3 "NOT IN USA THEN" 5 "DONT KNOW" 6 "MULT PUNCH" 7 "REFUSED" 8 "MISSING" 9 "LEGIT SKIP"
    label define LB21C 1 "YES" 2 "NO" 3 "NOT IN USA THEN" 5 "DONT KNOW" 6 "MULT PUNCH" 7 "REFUSED" 8 "MISSING" 9 "LEGIT SKIP"
    label define LB21D 1 "YES" 2 "NO" 3 "NOT IN USA THEN" 5 "DONT KNOW" 6 "MULT PUNCH" 7 "REFUSED" 8 "MISSING" 9 "LEGIT SKIP"
    label define LB22A 1 "YES" 2 "NO" 5 "DONT KNOW" 6 "MULT PUNCH" 7 "REFUSED" 8 "MISSING" 9 "LEGIT SKIP"
    label define LB22B 1 "YES" 2 "NO" 5 "DONT KNOW" 6 "MULT PUNCH" 7 "REFUSED" 8 "MISSING" 9 "LEGIT SKIP"
    label define LB22C 1 "YES" 2 "NO" 5 "DONT KNOW" 6 "MULT PUNCH" 7 "REFUSED" 8 "MISSING" 9 "LEGIT SKIP"
    label define LB22D 1 "YES" 2 "NO" 5 "DONT KNOW" 6 "MULT PUNCH" 7 "REFUSED" 8 "MISSING" 9 "LEGIT SKIP"
    label define LB23A 1 "ALL OR ALMOST" 2 "MOST" 3 "ABOUT HALF" 4 "SOME" 5 "NONE" 6 "NOT IN USA THEN" 95 "DONT KNOW" 96 "MULT PUNCH" 97 "REFUSED" 98 "MISSING" 99 "LEGIT SKIP"
    label define LB23B 1 "ALL OR ALMOST" 2 "MOST" 3 "ABOUT HALF" 4 "SOME" 5 "NONE" 6 "NOT IN USA THEN" 95 "DONT KNOW" 96 "MULT PUNCH" 97 "REFUSED" 98 "MISSING" 99 "LEGIT SKIP"
    label define LB23C 1 "ALL OR ALMOST" 2 "MOST" 3 "ABOUT HALF" 4 "SOME" 5 "NONE" 6 "NOT IN USA THEN" 95 "DONT KNOW" 96 "MULT PUNCH" 97 "REFUSED" 98 "MISSING" 99 "LEGIT SKIP"

    infile using "$dctdir/07896-0004.dct", using("$ICPSR_07896/DS0004/07896-0004-Data.txt")

    label data ICPSR_07896_0004

end
